
# 传入组
inputStruct:  
  robot_name: "qiaoyin"
  running_mode: 0 #运行模式0:idel, 1：手动， 2：自动， 3：数采
  enable: 0
  ctrl_cmd: 0 #0:初始状态， 1:启动， 2:停止， 3:暂停 

  arm_speed: 2.0  #m/s
  agv_move_speed: 2.0 #m/s
  q_arm_joints: #机器人下发关节角 左臂+右臂
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  q_arm_pos: #机器人下发笛卡尔 左臂+右臂
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  q_arm_pos:  #机器人当前笛卡尔 左臂+右臂
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  exp_arm_pos:  #机器人期望笛卡尔 左臂+右臂
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  gripper: [0,0]
  double q_agv_speed: [0.0, 0.0]  #机器人期望值 线速度+角速度


# 传出组
outputStruct:
  motor_on: 0
  gripper: [0, 0]
  q_agv_peed: [0, 0]    #机器人当前 线速度+角速度
  exp_agv_peed: [0, 0]    #机器人期望值 线速度+角速度
  robot_pos: [0, 0, 0]  #机器人在地图中的当前位置 x, y, rz
  q_arm_joints:  #机器人当前关节角 左臂+右臂
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  exp_arm_joints: #机器人期望关节角 左臂+右臂
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  q_arm_pos:  #机器人当前笛卡尔 左臂+右臂
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  exp_arm_pos:  #机器人期望笛卡尔 左臂+右臂
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  step:
    - id: 0
      descript: "Robot has been awakened"
    - id: 1
      descript: "Robot is moving to the garbage truck"
    - id: 2
      descript: "Robot is performing garbage truck positioning"
